export interface SPSSTestItem {
  id: string;
  name: string;
  category: 'Uji Dasar & Asumsi' | 'Korelasi & Bivariat' | 'Regresi & Instrumen' | 'Paket & Multivariat Kompleks';
  scope: string;
  price: number;
}

export const SPSS_TEST_LIST: SPSSTestItem[] = [
  // ── UJI DASAR & ASUMSI KLASIK ──────────────────────────
  { id: 'spss-1', name: 'Uji Deskriptif (mean, median, SD, frekuensi)', category: 'Uji Dasar & Asumsi', scope: 'Per dataset', price: 100000 },
  { id: 'spss-2', name: 'Uji Normalitas (Kolmogorov–Smirnov / Shapiro–Wilk)', category: 'Uji Dasar & Asumsi', scope: 'Per set variabel', price: 100000 },
  { id: 'spss-3', name: 'Uji Homogenitas (Levene’s Test)', category: 'Uji Dasar & Asumsi', scope: 'Per set variabel', price: 100000 },
  { id: 'spss-4', name: 'Uji Linearitas', category: 'Uji Dasar & Asumsi', scope: 'X dan Y', price: 150000 },
  { id: 'spss-5', name: 'Uji Multikolinearitas', category: 'Uji Dasar & Asumsi', scope: 'Model regresi', price: 150000 },
  { id: 'spss-6', name: 'Uji Heteroskedastisitas', category: 'Uji Dasar & Asumsi', scope: 'Model regresi', price: 150000 },
  { id: 'spss-7', name: 'Uji Autokorelasi (Durbin–Watson)', category: 'Uji Dasar & Asumsi', scope: 'Model regresi', price: 150000 },
  { id: 'spss-8', name: 'Uji Post Hoc (Tukey, Bonferroni, dll.)', category: 'Uji Dasar & Asumsi', scope: 'Tambahan', price: 100000 },
  { id: 'spss-9', name: 'KMO & Bartlett Test', category: 'Uji Dasar & Asumsi', scope: 'Tambahan EFA', price: 100000 },
  { id: 'spss-10', name: 'Pembuatan Dummy Data untuk SPSS', category: 'Uji Dasar & Asumsi', scope: 'Per dataset', price: 150000 },
  { id: 'spss-11', name: 'Cleaning & Coding Data (Siap Olah)', category: 'Uji Dasar & Asumsi', scope: 'Per dataset', price: 200000 },
  { id: 'spss-12', name: 'Uji Normal Q-Q Plot & Histogram', category: 'Uji Dasar & Asumsi', scope: 'Per dataset', price: 100000 },
  { id: 'spss-13', name: 'Uji Boxplot Outlier Detection', category: 'Uji Dasar & Asumsi', scope: 'Per variabel', price: 100000 },
  { id: 'spss-14', name: 'Uji Leverage & Cook’s Distance', category: 'Uji Dasar & Asumsi', scope: 'Model regresi', price: 150000 },
  { id: 'spss-15', name: 'Skewness & Kurtosis (Distribusi Data)', category: 'Uji Dasar & Asumsi', scope: 'Per variabel', price: 100000 },
  { id: 'spss-16', name: 'Transformasi Log / SQRT / Z-score', category: 'Uji Dasar & Asumsi', scope: 'Per variabel', price: 100000 },
  { id: 'spss-17', name: 'Uji Shapiro–Wilk per Kelompok', category: 'Uji Dasar & Asumsi', scope: 'Per kelompok data', price: 100000 },
  { id: 'spss-18', name: 'Uji Kolmogorov–Smirnov per Kelompok', category: 'Uji Dasar & Asumsi', scope: 'Per kelompok data', price: 100000 },
  { id: 'spss-19', name: 'Uji Levene per Variabel', category: 'Uji Dasar & Asumsi', scope: 'Per variabel', price: 100000 },
  { id: 'spss-20', name: 'Residual Normality Test (P-P Plot)', category: 'Uji Dasar & Asumsi', scope: 'Model regresi', price: 100000 },
  { id: 'spss-21', name: 'Residual Independence Check', category: 'Uji Dasar & Asumsi', scope: 'Model regresi', price: 100000 },
  { id: 'spss-22', name: 'Uji Boxplot Group Comparison', category: 'Uji Dasar & Asumsi', scope: 'Per kelompok', price: 100000 },

  // ── KORELASI, KOMPARASI & BIVARIAT ────────────────────
  { id: 'spss-23', name: 'Uji Korelasi (Pearson/Spearman)', category: 'Korelasi & Bivariat', scope: '2 variabel', price: 200000 },
  { id: 'spss-24', name: 'Uji Rank Spearman', category: 'Korelasi & Bivariat', scope: '2 variabel ordinal', price: 200000 },
  { id: 'spss-25', name: 'Uji Chi-Square', category: 'Korelasi & Bivariat', scope: '2–3 variabel kategori', price: 200000 },
  { id: 'spss-26', name: 'Uji T Independen', category: 'Korelasi & Bivariat', scope: '2 kelompok', price: 200000 },
  { id: 'spss-27', name: 'Uji T Berpasangan (Paired T-Test)', category: 'Korelasi & Bivariat', scope: '1 kelompok pre–post', price: 200000 },
  { id: 'spss-28', name: 'Uji Mann–Whitney', category: 'Korelasi & Bivariat', scope: '2 kelompok non-parametrik', price: 200000 },
  { id: 'spss-29', name: 'Uji Wilcoxon', category: 'Korelasi & Bivariat', scope: '1 kelompok pre–post (non-parametrik)', price: 200000 },
  { id: 'spss-30', name: 'Uji ANOVA One Way', category: 'Korelasi & Bivariat', scope: '≥ 3 kelompok', price: 300000 },
  { id: 'spss-31', name: 'Uji ANOVA Two Way', category: 'Korelasi & Bivariat', scope: '2 faktor', price: 350000 },
  { id: 'spss-32', name: 'Uji Kolerasi Partial', category: 'Korelasi & Bivariat', scope: '3 variabel (kontrol 1 variabel)', price: 250000 },
  { id: 'spss-33', name: 'Uji Kolerasi Berganda / Multiple Correlation', category: 'Korelasi & Bivariat', scope: '≥ 3 variabel', price: 300000 },
  { id: 'spss-34', name: 'Cross Tab + Chi-Square + Expected Count', category: 'Korelasi & Bivariat', scope: '2 variabel', price: 250000 },
  { id: 'spss-35', name: 'Uji Odds Ratio (Manual via Crosstab)', category: 'Korelasi & Bivariat', scope: '2 variabel', price: 200000 },
  { id: 'spss-36', name: 'Uji Crosstab Layering (Mantel-Haenszel)', category: 'Korelasi & Bivariat', scope: '3 variabel', price: 300000 },
  { id: 'spss-37', name: 'Weighted Mean Rank (Nonparametrik)', category: 'Korelasi & Bivariat', scope: 'Per dataset', price: 200000 },
  { id: 'spss-38', name: 'Uji Test for Randomness (Runs Test)', category: 'Korelasi & Bivariat', scope: 'Per dataset', price: 150000 },
  { id: 'spss-39', name: 'Uji Median Test', category: 'Korelasi & Bivariat', scope: '2–3 kelompok', price: 200000 },
  { id: 'spss-40', name: 'Uji Moses Extreme Reaction Test', category: 'Korelasi & Bivariat', scope: '2 kelompok', price: 200000 },
  { id: 'spss-41', name: 'Uji Kolmogorov–Smirnov Two Sample', category: 'Korelasi & Bivariat', scope: '2 kelompok', price: 200000 },
  { id: 'spss-42', name: 'Uji Cochran’s Q Test', category: 'Korelasi & Bivariat', scope: '≥ 3 pengukuran berulang (dikotomi)', price: 250000 },
  { id: 'spss-43', name: 'Uji McNemar', category: 'Korelasi & Bivariat', scope: '1 kelompok pre–post (kategori)', price: 200000 },
  { id: 'spss-44', name: 'Uji Fisher’s Exact Test', category: 'Korelasi & Bivariat', scope: '2 variabel kategori', price: 150000 },
  { id: 'spss-45', name: 'Uji Likelihood Ratio Chi-Square', category: 'Korelasi & Bivariat', scope: '2–3 variabel kategori', price: 200000 },
  { id: 'spss-46', name: 'Uji Lambda / Phi / Cramer’s V / Contingency Coefficient', category: 'Korelasi & Bivariat', scope: '2 variabel kategori', price: 200000 },
  { id: 'spss-47', name: 'Uji Gamma / Somers’ D / Kendall’s Tau-b', category: 'Korelasi & Bivariat', scope: '2 variabel ordinal', price: 200000 },
  { id: 'spss-48', name: 'Uji Tukey B / Duncan / Scheffe (Post Hoc)', category: 'Korelasi & Bivariat', scope: 'Tambahan', price: 100000 },
  { id: 'spss-49', name: 'Uji Student–Newman–Keuls (Post Hoc)', category: 'Korelasi & Bivariat', scope: 'Tambahan', price: 100000 },

  // ── REGRESI, VALIDITAS & INSTRUMEN ───────────────────
  { id: 'spss-50', name: 'Uji Regresi Linear Sederhana', category: 'Regresi & Instrumen', scope: '2 variabel (X → Y)', price: 250000 },
  { id: 'spss-51', name: 'Uji Regresi Linear Berganda', category: 'Regresi & Instrumen', scope: '≥ 3 variabel', price: 300000 },
  { id: 'spss-52', name: 'Uji Regresi Logistik', category: 'Regresi & Instrumen', scope: '1 DV kategorik + beberapa IV', price: 350000 },
  { id: 'spss-53', name: 'Uji Validitas (Pearson)', category: 'Regresi & Instrumen', scope: 'Per konstruk (≥ 10 item)', price: 250000 },
  { id: 'spss-54', name: 'Uji Reliabilitas (Cronbach’s Alpha)', category: 'Regresi & Instrumen', scope: 'Per konstruk', price: 200000 },
  { id: 'spss-55', name: 'Uji Faktor (Exploratory Factor Analysis / EFA)', category: 'Regresi & Instrumen', scope: '10–30 item', price: 400000 },
  { id: 'spss-56', name: 'Konversi Data (Ordinal ke Interval – MSI)', category: 'Regresi & Instrumen', scope: 'Per konstruk', price: 200000 },
  { id: 'spss-57', name: 'Uji Goodness of Fit Regresi Logistik (Hosmer–Lemeshow)', category: 'Regresi & Instrumen', scope: 'Model logistik', price: 150000 },
  { id: 'spss-58', name: 'ROC Curve & AUC Analysis', category: 'Regresi & Instrumen', scope: 'Model klasifikasi', price: 250000 },
  { id: 'spss-59', name: 'Uji R-Square Change (Regresi Hierarki Manual)', category: 'Regresi & Instrumen', scope: '2–3 blok variabel', price: 300000 },
  { id: 'spss-60', name: 'Uji Reliability Composite (Estimasi SPSS Manual)', category: 'Regresi & Instrumen', scope: 'Per konstruk', price: 250000 },
  { id: 'spss-61', name: 'Item Analysis (Corrected Item-Total Correlation)', category: 'Regresi & Instrumen', scope: '≥ 10 item', price: 250000 },
  { id: 'spss-62', name: 'Uji Weighted Kappa / Agreement (SPSS)', category: 'Regresi & Instrumen', scope: '2 rater', price: 300000 },
  { id: 'spss-63', name: 'Inter Rater Reliability (Percent Agreement / Kappa)', category: 'Regresi & Instrumen', scope: '2–5 rater', price: 300000 },
  { id: 'spss-64', name: 'Uji Partial Eta Squared (ANOVA/ANCOVA)', category: 'Regresi & Instrumen', scope: 'Per model', price: 150000 },
  { id: 'spss-65', name: 'Uji Omega Squared (Manual SPSS)', category: 'Regresi & Instrumen', scope: 'Per model', price: 200000 },
  { id: 'spss-66', name: 'Uji Power Analysis (Manual SPSS Output)', category: 'Regresi & Instrumen', scope: 'Per uji', price: 200000 },
  { id: 'spss-67', name: 'Uji Reliability Test–Retest (2 waktu)', category: 'Regresi & Instrumen', scope: '1 konstruk', price: 250000 },
  { id: 'spss-68', name: 'Uji Bartlett’s Sphericity (Standalone)', category: 'Regresi & Instrumen', scope: 'Per konstruk', price: 150000 },
  { id: 'spss-69', name: 'Interaction Term (Regresi)', category: 'Regresi & Instrumen', scope: '3 variabel (X, Z, XZ)', price: 300000 },
  { id: 'spss-70', name: 'Complex Dummy Coding (>3 kategori)', category: 'Regresi & Instrumen', scope: 'Per variabel', price: 150000 },
  { id: 'spss-71', name: 'Pembuatan Index Komposit (Averaging/Z-score)', category: 'Regresi & Instrumen', scope: 'Per konstruk', price: 200000 },
  { id: 'spss-72', name: 'Rekap Output + Tabel Siap Publikasi', category: 'Regresi & Instrumen', scope: 'Per analisis', price: 150000 },

  // ── PAKET & MULTIVARIAT KOMPLEKS ─────────────────────
  { id: 'spss-73', name: 'Paket Olah Data Lengkap SPSS (Semua Uji Sederhana)', category: 'Paket & Multivariat Kompleks', scope: 'Deskriptif + Normalitas + T/ANOVA/Korelasi', price: 650000 },
  { id: 'spss-74', name: 'MANOVA (Multivariate ANOVA)', category: 'Paket & Multivariat Kompleks', scope: '≥ 2 DV + 1 faktor', price: 600000 },
  { id: 'spss-75', name: 'MANCOVA', category: 'Paket & Multivariat Kompleks', scope: '≥ 2 DV + faktor + kovariat', price: 700000 },
  { id: 'spss-76', name: 'Mixed Model (Between–Within ANOVA)', category: 'Paket & Multivariat Kompleks', scope: 'Kelompok + waktu', price: 700000 },
  { id: 'spss-77', name: 'Repeated Measures ANOVA + Post Hoc + Effect Size', category: 'Paket & Multivariat Kompleks', scope: '≥ 3 waktu', price: 650000 },
  { id: 'spss-78', name: 'General Linear Model (GLM Full Model)', category: 'Paket & Multivariat Kompleks', scope: '≥ 5 variabel', price: 700000 },
  { id: 'spss-79', name: 'Generalized Linear Model (GLM Binomial/Poisson)', category: 'Paket & Multivariat Kompleks', scope: 'Model khusus distribusi', price: 750000 },
  { id: 'spss-80', name: 'Hierarchical / Blockwise Regression (3–4 blok)', category: 'Paket & Multivariat Kompleks', scope: '≥ 6 variabel', price: 700000 },
  { id: 'spss-81', name: 'Stepwise / Forward / Backward Regression', category: 'Paket & Multivariat Kompleks', scope: '≥ 8 variabel', price: 650000 },
  { id: 'spss-82', name: 'Binary Logistic Regression Full + Diagnostics', category: 'Paket & Multivariat Kompleks', scope: '≥ 6 variabel', price: 700000 },
  { id: 'spss-83', name: 'Multinomial Logistic Regression', category: 'Paket & Multivariat Kompleks', scope: 'DV > 2 kategori', price: 850000 },
  { id: 'spss-84', name: 'Ordinal Logistic Regression (PLUM)', category: 'Paket & Multivariat Kompleks', scope: 'DV ordinal', price: 850000 },
  { id: 'spss-85', name: 'Discriminant Analysis (Full Model)', category: 'Paket & Multivariat Kompleks', scope: '≥ 3 kelompok', price: 800000 },
  { id: 'spss-86', name: 'Cluster Analysis (Hierarchical + K-Means Kombinasi)', category: 'Paket & Multivariat Kompleks', scope: 'Full dataset', price: 900000 },
  { id: 'spss-87', name: 'Two-Step Cluster Analysis', category: 'Paket & Multivariat Kompleks', scope: 'Data besar / campuran', price: 1000000 },
  { id: 'spss-88', name: 'Time Series – Trend & Seasonal Decomposition', category: 'Paket & Multivariat Kompleks', scope: '≥ 36 periode', price: 850000 },
  { id: 'spss-89', name: 'ARIMA / Forecasting SPSS', category: 'Paket & Multivariat Kompleks', scope: 'Time series', price: 1200000 },
  { id: 'spss-90', name: 'Kaplan–Meier Survival Analysis (SPSS)', category: 'Paket & Multivariat Kompleks', scope: 'Survival DV', price: 1000000 },
  { id: 'spss-91', name: 'Cox Regression (Hazard Model – SPSS)', category: 'Paket & Multivariat Kompleks', scope: 'Survival + covariat', price: 1300000 },
  { id: 'spss-92', name: 'Bayesian Decision / Classification (Manual SPSS)', category: 'Paket & Multivariat Kompleks', scope: 'Kategori DV', price: 1200000 },
  { id: 'spss-93', name: 'Multiple Imputation (5–10 imputasi)', category: 'Paket & Multivariat Kompleks', scope: 'Dataset missing', price: 1000000 },
  { id: 'spss-94', name: 'Bootstrapping 1.000 Sampel (Full Model)', category: 'Paket & Multivariat Kompleks', scope: 'Model regresi/logistik', price: 1100000 },
  { id: 'spss-95', name: 'Monte Carlo Simulation (Manual SPSS)', category: 'Paket & Multivariat Kompleks', scope: 'Model kompleks', price: 1500000 },
  { id: 'spss-96', name: 'Propensity Score Matching (Manual SPSS)', category: 'Paket & Multivariat Kompleks', scope: '≥ 2 kelompok', price: 1300000 },
  { id: 'spss-97', name: 'Mahalanobis Distance Matching (Manual)', category: 'Paket & Multivariat Kompleks', scope: '≥ 2 kelompok', price: 1400000 },
  { id: 'spss-98', name: 'Big Dataset Optimization (>50.000 data)', category: 'Paket & Multivariat Kompleks', scope: 'Full proses', price: 1500000 },
];
